config/routes.rb
Rails.application.routes.draw do
  get 'data_deletion/facebook_deletion'
  get 'password_resets/new'
  get 'password_resets/edit--no-test-framework'
  # root "articles#index"
  root "static_pages#home"

  # Defines the root path route ("/")
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers, :settings
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  get '/microposts', to: 'static_pages#home'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: redirect('/')
  post '/auth/:provider/callback', to: 'sessions#create'
  resources :microposts do
    resources :comments do
      member do
        delete :destroy
      end
    end
    member do
      post :reply
    end
    resources :reactions, only: [:create, :destroy]
  end
  resources :comments do
    resources :reactions, only: [:create, :destroy]
  end
  resources :chat_rooms, only: [:index, :show, :create]
  get 'messages', to: 'chat_rooms#index'
  mount ActionCable.server => '/cable'
  resources :chat_rooms do
    resources :messages
  end
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :chat_room_participants, dependent: :destroy
  has_many :users, through: :chat_room_participants
  has_many :messages, dependent: :destroy

  def participant?(user)
    users.include?(user)
  end
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  before_action :logged_in_user

  def index
    @chat_rooms = current_user.chat_rooms.includes(:users)
  end

  def show
    @chat_room = ChatRoom.find(params[:id])
    @messages = @chat_room.messages.includes(:user)
    @message = Message.new
  end

  def create
    @other_user = User.find(params[:user_id])
    # Kiểm tra xem đã có chat room giữa 2 user chưa
    @chat_room = find_or_create_chat_room(@other_user)
    redirect_to @chat_room
  end

  private

  def find_or_create_chat_room(other_user)
    # Tìm chat room chung giữa current_user và other_user
    common_room = ChatRoom.joins(:chat_room_participants)
                         .where(chat_room_participants: { user_id: [current_user.id, other_user.id] })
                         .group('chat_rooms.id')
                         .having('COUNT(DISTINCT chat_room_participants.user_id) = 2')
                         .first

    return common_room if common_room

    # Nếu chưa có thì tạo mới
    ChatRoom.transaction do
      room = ChatRoom.create!
      room.chat_room_participants.create!(user: current_user)
      room.chat_room_participants.create!(user: other_user)
      room
    end
  end
end

app/views/chat_rooms/index.html.erb
<div class="chat-rooms-container">
  <h1>Messages</h1>
  
  <% if @chat_rooms.any? %>
    <div class="chat-rooms-list">
      <% @chat_rooms.each do |room| %>
        <div class="chat-room-item">
          <% other_user = room.users.where.not(id: current_user.id).first %>
          <%= link_to chat_room_path(room), class: "chat-room-link" do %>
            <div class="user-info">
              <%= gravatar_for other_user, size: 50 %>
              <div class="user-details">
                <span class="user-name"><%= other_user.name %></span>
                <% if room.messages.any? %>
                  <span class="last-message">
                    <%= truncate(room.messages.last.content, length: 50) %>
                  </span>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  <% else %>
    <div class="no-messages">
      <p>No messages yet. Visit a user's profile to start a conversation!</p>
    </div>
  <% end %>
</div>

app/views/chat_rooms/show.html.erb
<div class="chat-room">
  <div class="messages" id="messages" data-chat-room-id="<%= @chat_room.id %>">
    <%= render @messages if @messages.any? %>
  </div>

  <div class="message-form">
    <%= form_with(model: [@chat_room, @message], 
                  remote: true,
                  html: { class: 'message-form' }) do |f| %>
      <div class="field">
        <%= f.text_area :content, class: 'form-control' %>
      </div>
      <%= f.submit "Send", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>