config/routes.rb
Rails.application.routes.draw do
  get 'data_deletion/facebook_deletion'
  get 'password_resets/new'
  get 'password_resets/edit--no-test-framework'
  # root "articles#index"
  root "static_pages#home"

  # Defines the root path route ("/")
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers, :settings
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  get '/microposts', to: 'static_pages#home'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: redirect('/')
  post '/auth/:provider/callback', to: 'sessions#create'
  resources :microposts do
    resources :comments do
      member do
        delete :destroy
      end
    end
    member do
      post :reply
    end
    resources :reactions, only: [:create, :destroy]
  end
  resources :comments do
    resources :reactions, only: [:create, :destroy]
  end
  resources :chat_rooms, only: [:index, :show, :create]
  get 'messages', to: 'chat_rooms#index'
  mount ActionCable.server => '/cable'
  resources :chat_rooms do
    resources :messages
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts, dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save   :downcase_email
  before_create :create_activation_digest
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  has_many :comments, dependent: :destroy
  has_many :chat_room_participants
  has_many :chat_rooms, through: :chat_room_participants
  has_many :messages

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
    remember_digest
  end

  # Returns a session token to prevent session hijacking.
  # We reuse the remember digest for convenience.
  def session_token
    remember_digest || remember
  end

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Activates an account.
  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  # Returns a user's status feed.
  def feed
    following_ids = "SELECT followed_id FROM relationships
                    WHERE  follower_id = :user_id"
    Micropost.where("user_id IN (#{following_ids})
                    OR user_id = :user_id", user_id: id)
  end

  # Follows a user.
  def follow(other_user)
    following << other_user unless self == other_user
  end

  # Unfollows a user.
  def unfollow(other_user)
    following.delete(other_user)
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = SecureRandom.hex(15)
      user.name = auth.info.name
      user.username = auth.info.nickname
      user.avatar_url = auth.info.image
      user.github_url = auth.info.urls&.GitHub
      user.activated = true
    end
  end

  private

    # Converts email to all lowercase.
    def downcase_email
      self.email = email.downcase
    end

    # Creates and assigns the activation token and digest.
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy,
                                        :following, :followers]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    # Before filters

    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper

    # Returns the Gravatar for the given user.
    def gravatar_for(user, options = { size: 80 })
        size         = options[:size]
        gravatar_id  = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end

    def avatar_for(user, options = { size: 80 })
        if user.avatar_url.present?
            image_tag user.avatar_url, class: "avatar-#{options[:size]}", 
                                    alt: user.name,
                                    style: "width: #{options[:size]}px; height: #{options[:size]}px;"
        else
            # Fallback avatar nếu không có avatar từ GitHub
            image_tag "default-avatar.png", class: "avatar-#{options[:size]}"
        end
    end
end

app/views/users/_follow.html.erb
<%= form_with(model: current_user.active_relationships.build, local: false) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= form_with(model: current_user.active_relationships.find_by(followed_id: @user.id),
                  html: { method: :delete }, local: true) do |f| %>
      <%= f.submit "Unfollow", class: "btn btn-primary follow-btn" %>
    <% end %>
  <% else %>
    <%= form_with(model: current_user.active_relationships.build, local: true) do |f| %>
      <%= hidden_field_tag :followed_id, @user.id %>
      <%= f.submit "Follow", class: "btn btn-primary follow-btn" %>
    <% end %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_with(model: current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
    <%= gravatar_for user, size: 20 %>
    <%= link_to user.name, user %>
    <% if current_user.admin? && !current_user?(user) %> | <%= link_to "delete", user, method: :delete, data: { confirm: "You sure?" } %>
    <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="user-avatar-container">
            <% if @user.avatar_url.present? %>
                <%= image_tag @user.avatar_url, class: "avatar-profile", style: "width: 100px; height: 100px;" %>
            <% end %>
        </div>

        <%= form_with(model: @user, local: true) do |f| %>
            <%= render 'shared/error_messages', object: f.object %>

            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>

            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>

            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>

            <%= f.label :password_confirmation, "Confirmation" %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>

            <%= f.submit "Save changes", class: "btn btn-primary" %>
        <% end %>

        <div class="gravatar_edit">
            <%= gravatar_for @user %>
            <a href="https://gravatar.com/emails" target="_blank">change</a>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<ul class="users">
  <%= render @users %>
</ul>

<div class="pagination justify-content-center">
  <%= will_paginate @users, 
                    renderer: WillPaginate::ActionView::BootstrapLinkRenderer,
                    previous_label: '&laquo;',
                    next_label: '&raquo;' %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_with(model: @user, local: true) do |f| %>
            <%= render 'shared/error_messages', object: f.object %>
    
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
    
            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>
    
            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>
    
            <%= f.label :password_confirmation, "Confirmation" %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
    
            <%= f.submit "Create my account", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <div class="profile-header text-center">
        <% if @user.avatar_url.present? %>
          <%= image_tag @user.avatar_url, class: "github-avatar" , style: "width: 100px; height: 100px;" %>
        <% end %>
        <h1><%= @user.name %></h1>
        
        <%= link_to "GitHub Profile", @user.github_url, 
            class: "btn btn-dark github-btn", 
            target: "_blank" if @user.github_url.present? %>
        
        <div class="github-stats">
          <span><%= pluralize(0, 'follower') %></span>
          <span><%= pluralize(0, 'following') %></span>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <div class="profile-header">
        <%= gravatar_for @user %>
        <h1><%= @user.name %></h1>
        <div class="stats">
          <span class="stat">
            <span class="count"><%= pluralize(@user.followers.count, "follower") %></span>
          </span>
          <span class="stat">
            <span class="count"><%= pluralize(@user.following.count, "following") %></span>
          </span>
        </div>
        <div class="action-buttons">
          <%= render 'follow_form' if logged_in? && !current_user?(@user) %>
          <% if logged_in? && !current_user?(@user) %>
            <%= button_to "Message", chat_rooms_path(user_id: @user.id), 
                         method: :post, 
                         class: "btn btn-primary message-btn" %>
          <% end %>
        </div>
      </div>
    </section>
  </aside>
  
  <div class="col-md-8">
    <h3>Microposts (<%= @user.microposts.count %>)</h3>
    <ol class="microposts">
      <%= render @microposts %>
    </ol>
    <%= will_paginate @microposts %>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Microposts:</b> <%= @user.microposts.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>